[pytest]
pythonpath = .
addopts = -p no:pytest_asyncio
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*
    ignore:Conversion of an array with ndim > 0 to a scalar is deprecated.*:DeprecationWarning
